// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  var creeps, governors, logger, roles, rooms, spawns, tasks, tick, u;

  // hotpatching
  creeps = require('creeps');

  rooms = require('rooms');

  roles = require('roles');

  tasks = require('tasks');

  spawns = require('spawns');

  governors = require('governors');

  creeps = require('creeps');

  logger = require('logger');

  u = require('utils');

  // ticks:
  // every:
  //   core functionality
  // :
  //   governor
  tick = function() {
    var cName, creep, gName, gov, rName, ref, ref1, ref2, ref3, ref4, results, room;
    logger.trace('beginning tick');
    ref = Game.rooms;
    for (rName in ref) {
      room = ref[rName];
      room.init();
      if (u.onFreq(u.freq.RARELY)) {
        governors.delIfRequired(room);
        governors.newIfRequired(room);
      }
      ref1 = room.memory.governors;
      for (gName in ref1) {
        gov = ref1[gName];
        gov.tick();
        gov.updateEdicts();
      }
    }
    ref2 = Game.creeps;
    for (cName in ref2) {
      creep = ref2[cName];
      creep.init();
    }
    ref3 = Game.spawns;
    for (rName in ref3) {
      room = ref3[rName];
      "";
    }
    ref4 = Game.structures;
    results = [];
    for (rName in ref4) {
      room = ref4[rName];
      results.push("");
    }
    return results;
  };

  module.exports = {
    loop: tick
  };

}).call(this);
